# Docker
###
version: '3.0'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000



#Postgresql
###step2で追加
db: 
  image: postgres:14.4-alpine
  container_name: postgres_sql


  # image 作成時の初期設定
  environment: 
    ENV LANG: ja_JP.UTF-8 # postgres内の文字コードを指定
    TZ: Asia/Tokyo  # postgres内のTimeZoneを指定
    POSTGRES_DB: Incident
    POSTGRES_PASSWORD: postgresql

    # Postgresに接続するためのポート（外部からのアクセス時のポート：docker内部からのアクセス時のポート）
    ports:
      - "5436:5436"

    volumes: 
      - ./script:/docker-entrypoint-initdb.d    # 追加(scriptフォルダ内にあるスクリプトを実行する。)
      - db-store:/var/lib/postgresql/data       # DBデータ永続化

# DBデータ永続化
volumes:
  db-store: